services:

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    env_file:
      - .env.test
    depends_on:
      test_postgres:
        condition: service_healthy
    command: pytest tests/ -v --cov=app