services:
  test_postgres:
    image: postgres:15
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    env_file:
      - .env.test
    depends_on:
      test_postgres:
        condition: service_healthy
    command: pytest tests/ -v --cov=app