FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements_test.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements_test.txt

COPY . .

CMD ["pytest", "-v", "--asyncio-mode=auto"]