services:

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      start_period: 10s       # Wait 10 seconds before the first health check
      interval: 60s          # Check every 60 seconds after that
      retries: 5             # Retry 5 times if health check fails
      timeout: 5s

volumes:
  postgres_data: