name: Docker Compose Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "DB_USER is set: ${{ env.DB_USER != '' }}"
          echo "DB_PASSWORD is set: ${{ env.DB_PASSWORD != '' }}"
          echo "DB_NAME is set: ${{ env.DB_NAME != '' }}"
          echo "DB_PORT is set: ${{ env.DB_PORT != '' }}"

      - name: Debug Docker Compose
        run: docker compose -f docker-compose.test.yaml --env-file .env.test config

      - name: Build and run tests
        run: |
          docker compose -f docker-compose.test.yaml up \
            --build \
            --exit-code-from test \
            --abort-on-container-exit