name: Docker Compose Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          # Remove quotes and use direct assignment
          echo "DB_USER=${DB_USER}" > .env.test
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env.test
          echo "DB_NAME=${DB_NAME}" >> .env.test
          echo "DB_PORT=${DB_PORT}" >> .env.test
          echo "DB_HOST=${DB_HOST}" >> .env.test
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}

      - name: Verify .env.test (masked)
        run: sed 's/=.*$/=***/' .env.test

      - name: Build and run tests
        run: |
          docker compose -f docker-compose.test.yaml up \
            --build \
            --exit-code-from test \
            --abort-on-container-exit